# src/gen_rec_lines.py
"""
Optional helper script.
The main generator (gen_mock_dataset.py) already produces
cropped line images and TSV labels for recognizer training.

This script is a placeholder if you want to add extra synthetic
text lines for recognizer pretraining.
"""

import sys
print("Recognizer line crops are already generated by gen_mock_dataset.py")
sys.exit(0)
